# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

env:
  ghidra-url: https://ghidra-sre.org/ghidra_9.1.2_PUBLIC_20200212.zip
  ghidra-zip-filename: ghidra_9.1.2_PUBLIC.zip
  ghidra-directory: ghidra_9.1.2_PUBLIC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download Ghidra release
      uses: carlosperate/download-file-action@v1.0.3
      id: download-ghidra
      with:
        file-url: ${{ env.ghidra-url }}
        file-name: ${{ env.ghidra-zip-filename }}
        location: '.'
    - name: Print the file path
      run: echo "The file was downloaded to ${{ steps.download-ghidra.outputs.file-path }}"
    - name: Unzip Ghidra
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ${{ steps.download-ghidra.outputs.file-path }} -d .
    - uses: actions/setup-java@v1
      with:
        java-version: 11.0.2
    - name: Build extension
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: '5.0'
        build-root-directory: ghidra-nsis-extension/nsis
        arguments: -PGHIDRA_INSTALL_DIR=../../${{ ghidra-directory }}
